basePath: /api/v1
definitions:
  models.AccessMenu:
    properties:
      _id:
        type: string
      accesssubmenu:
        items:
          $ref: '#/definitions/models.AccessSubmenu'
        type: array
      create:
        type: boolean
      delete:
        type: boolean
      idmenu:
        type: string
      idrole:
        type: string
      read:
        type: boolean
      update:
        type: boolean
    required:
    - _id
    - create
    - delete
    - idmenu
    - idrole
    - read
    - update
    type: object
  models.AccessSubmenu:
    properties:
      create:
        type: boolean
      delete:
        type: boolean
      idsubmenu:
        type: integer
      read:
        type: boolean
      update:
        type: boolean
    required:
    - create
    - delete
    - idsubmenu
    - read
    - update
    type: object
  models.DefaultResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  models.LoginRequest:
    description: The structure of login request with username and password.
    properties:
      duration:
        description: '@description The duration of the login session in hours (optional).'
        type: integer
      idcompany:
        description: '@description The company ID of the user (optional).'
        type: string
      password:
        description: |-
          @required
          @description The password of the user.
        type: string
      rememberpassword:
        description: '@description Whether to remember the user''s password (optional).'
        type: boolean
      username:
        description: |-
          @required
          @description The username of the user.
        type: string
    required:
    - password
    - username
    type: object
  models.LoginResponse:
    description: The structure of the login response.
    properties:
      access:
        description: '@description The access menu available for the user after login,
          including submenus.'
        items:
          $ref: '#/definitions/models.AccessMenu'
        type: array
      expired:
        description: '@description The expiration time of the generated token.'
        type: string
      idcompany:
        description: '@description The company ID of the user (optional).'
        type: string
      islogin:
        description: '@description Indicates whether the user is successfully logged
          in.'
        type: boolean
      ismaintenance:
        description: '@description Indicates whether the system is under maintenance.'
        type: boolean
      token:
        description: '@description The token generated for the user after login.'
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: sitompulsalomo@gmail.com
    name: salomo07
  description: All API for SCM.
  title: SCM  API (Go Swagger)
  version: 1.0.0
paths:
  /Auth/Login:
    post:
      description: Login
      parameters:
      - description: Login request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      responses:
        "200":
          description: Successful login
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.DefaultResponse'
schemes:
- http
- https
swagger: "2.0"
